[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/backend/:splat"
    status = 200


[functions]
  directory = "src/netlify/functions"
  node_bundler = "esbuild"
    included_files=["src/assets/jmdict/*.json"]
    external_node_modules = ["kuromoji"]  